package dhbw.graphmetrics.metrics;

public enum NodeMetric {
	DEGREE,
	OUT_DEGREE,
	IN_DEGREE,
	ECCENTRICITY,
	DEGREE_CENTRALITY,
	BETWEENNESS_CENTRALITY,
	CLOSENESS_CENTRALITY,
	EIGENVECTOR_CENTRALITY,
	PAGE_RANK
}