package dhbw.graphmetrics.metrics;

/**
 * Enumeration holding the different node metrics
 */
public enum NodeMetric {
	DEGREE,
	OUT_DEGREE,
	IN_DEGREE,
	ECCENTRICITY,
	DEGREE_CENTRALITY,
	BETWEENNESS_CENTRALITY,
	CLOSENESS_CENTRALITY,
	CLOSENESS_CENTRALITY_DISCONNECTED,
	EIGENVECTOR_CENTRALITY,
	EIGENVECTOR_CENTRALITY_NORMALIZED,
	PAGE_RANK
}